// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mukshpfevymcsfwtsylt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11a3NocGZldnltY3Nmd3RzeWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNDIwOTEsImV4cCI6MjA3MzcxODA5MX0.086hDPqV0UmQ6Tkci_li8l284YPQpLaIjiwTGo4CKaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});